services:
  app:
    image: sae-virtu
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/pokedex
    command: ["npm", "start"]
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pokedex
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: